ComposantFamilles={
    "Pere",
    "Mere",
    "Fis",
    "Fille",
     "Petit-Fils",
     "Petite-Fille",
     "Arriere-Petit-Fils",
     "Arriere-Petite-Fille",
     "Grand-Pere",
     "Grand-Mere",
     "Gendre",
     "Bru",
     "Beau-Pere",
     "Belle-Mere",
     "Oncle",
     "Tante",
     "Grand-Oncle",
     "Grand-Tante",
     "Grand-Cousin",
     "Grande-Cousine",
     "Beau-Fils",
     "Belle-Fille",
     "Petit-Neveu",
     "Petite-Niece",
     "Arriere-Petit-Neveu",
     "Arriere-Petite-Niece",
     "Cousin Germain",
     "Cousine Germaine",
     "Cousin",
     "Cousine",
     "Petit-Cousin",
     "Petit-Cousine",
     "Arriere-Cousin",
     "Arriere-Cousine",
}

const NbreComposantsFamilles = ComposantsFamilles.length;